#!/bin/bash


echo "Testing new protobuf files"

CURRENT_API_DIR=$1
NEW_API_DIR=$2

for filename in ${CURRENT_API_DIR}/nlu/*pb2*; do
    base_name=$(basename ${filename})
    #echo $base_name
    if [ -e  ./${NEW_API_DIR}/nlu/${base_name} ]; then
        #echo "Found protobuf file ${base_name}" 
        continue
    else
        echo "Missing protobuf file: ${base_name}"
        echo "Test failed" >&2
        exit 1
    fi
done

echo "Test passed"
echo "Protobuf files are preserved"

exit 0
