# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from typing import (
    Any,
    Dict,
    Optional,
    Set,
    Tuple,
)

from ondewo.utils.base_client import BaseClient
from ondewo.utils.base_client_config import BaseClientConfig

from ondewo.nlu.client_config import ClientConfig
from ondewo.nlu.core.services_container import ServicesContainer
from ondewo.nlu.services.agents import Agents
from ondewo.nlu.services.aiservices import AiServices
from ondewo.nlu.services.ccai_projects import CcaiProjects
from ondewo.nlu.services.contexts import Contexts
from ondewo.nlu.services.entity_types import EntityTypes
from ondewo.nlu.services.intents import Intents
from ondewo.nlu.services.llm_evaluations import LlmEvaluations
from ondewo.nlu.services.operations import Operations
from ondewo.nlu.services.project_roles import ProjectRoles
from ondewo.nlu.services.project_statistics import ProjectStatistics
from ondewo.nlu.services.rags import Rags
from ondewo.nlu.services.server_statistics import ServerStatistics
from ondewo.nlu.services.sessions import Sessions
from ondewo.nlu.services.users import Users
from ondewo.nlu.services.utilities import Utilities
from ondewo.nlu.services.webhooks import Webhook


class Client(BaseClient):
    """
    The core python client for interacting with ONDEWO NLU services.
    """

    def __init__(
        self,
        config: BaseClientConfig,
        use_secure_channel: bool = True,
        options: Optional[Set[Tuple[str, Any]]] = None,
        *,
        use_shared_channel: bool = False,
    ) -> None:
        """
        Initialize the client and its service clients.

        Args:
            config (BaseClientConfig):
                Configuration for the client; must be an ``ondewo.nlu.client_config.ClientConfig``.
            use_secure_channel (bool):
                Whether to use a secure gRPC channel. Defaults to ``True``.
            options (Optional[Set[Tuple[str, Any]]]):
                Additional options for the gRPC channel. Defaults to ``None``.
            use_shared_channel (bool):
                Open ONE gRPC channel for all services (one connection, one TLS handshake) instead of
                one per service. Kept by ``connect`` after a ``disconnect``. Needs Python >= 3.12
                (ondewo-client-utils >= 4.0.0). Defaults to ``False``.
        """
        self.use_shared_channel: bool = use_shared_channel
        super().__init__(config=config, use_secure_channel=use_secure_channel, options=options)

    def _initialize_services(
        self,
        config: BaseClientConfig,
        use_secure_channel: bool,
        options: Optional[Set[Tuple[str, Any]]] = None,
    ) -> None:
        """

        Initialize the service clients with the current config and set up the services in self.services

        Args:
            config (BaseClientConfig):
                Configuration for the client.
            use_secure_channel (bool):
                Whether to use a secure gRPC channel.
            options (Optional[Set[Tuple[str, Any]]]):
                Additional options for the gRPC channel.
        """
        if not isinstance(config, ClientConfig):
            raise ValueError("The provided config must be of type `ondewo.nlu.client_config.ClientConfig`")

        kwargs: Dict[str, Any] = {
            "config": config,
            "use_secure_channel": use_secure_channel,
            "options": options,
        }
        if self.use_shared_channel:
            # Imported here: ondewo-client-utils < 4.0.0 (Python < 3.12) has no build_shared_channel.
            from ondewo.utils.base_services_interface import build_shared_channel

            kwargs["grpc_channel"] = build_shared_channel(
                config=config,
                use_secure_channel=use_secure_channel,
                service_classes=(
                    Agents,
                    AiServices,
                    CcaiProjects,
                    Contexts,
                    EntityTypes,
                    Intents,
                    LlmEvaluations,
                    Operations,
                    ProjectRoles,
                    ProjectStatistics,
                    Rags,
                    ServerStatistics,
                    Sessions,
                    Users,
                    Utilities,
                    Webhook,
                ),
                options=options,
            )
        self.services: ServicesContainer = ServicesContainer(
            agents=Agents(**kwargs),
            aiservices=AiServices(**kwargs),
            ccai_projects=CcaiProjects(**kwargs),
            contexts=Contexts(**kwargs),
            entity_types=EntityTypes(**kwargs),
            intents=Intents(**kwargs),
            llm_evaluations=LlmEvaluations(**kwargs),
            operations=Operations(**kwargs),
            project_roles=ProjectRoles(**kwargs),
            project_statistics=ProjectStatistics(**kwargs),
            rags=Rags(**kwargs),
            server_statistics=ServerStatistics(**kwargs),
            sessions=Sessions(**kwargs),
            users=Users(**kwargs),
            utilities=Utilities(**kwargs),
            webhooks=Webhook(**kwargs),
        )
