# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.any_pb2 import (
    Any as google___protobuf___any_pb2___Any,
)

from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
    RepeatedScalarFieldContainer as google___protobuf___internal___containers___RepeatedScalarFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from google.protobuf.timestamp_pb2 import (
    Timestamp as google___protobuf___timestamp_pb2___Timestamp,
)

from google.rpc.status_pb2 import (
    Status as google___rpc___status_pb2___Status,
)

from ondewo.nlu.operation_metadata_pb2 import (
    OperationMetadata as ondewo___nlu___operation_metadata_pb2___OperationMetadata,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
    Union as typing___Union,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int
if sys.version_info < (3,):
    builtin___buffer = buffer
    builtin___unicode = unicode


class Operation(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    done = ... # type: builtin___bool

    @property
    def metadata(self) -> google___protobuf___any_pb2___Any: ...

    @property
    def error(self) -> google___rpc___status_pb2___Status: ...

    @property
    def response(self) -> google___protobuf___any_pb2___Any: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        metadata : typing___Optional[google___protobuf___any_pb2___Any] = None,
        done : typing___Optional[builtin___bool] = None,
        error : typing___Optional[google___rpc___status_pb2___Status] = None,
        response : typing___Optional[google___protobuf___any_pb2___Any] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> Operation: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> Operation: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"error",b"error",u"metadata",b"metadata",u"response",b"response",u"result",b"result"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"done",b"done",u"error",b"error",u"metadata",b"metadata",u"name",b"name",u"response",b"response",u"result",b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"result",b"result"]) -> typing_extensions___Literal["error","response"]: ...
global___Operation = Operation

class GetOperationRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> GetOperationRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> GetOperationRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name"]) -> None: ...
global___GetOperationRequest = GetOperationRequest

class ListOperationsRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text
    filter = ... # type: typing___Text
    page_size = ... # type: builtin___int
    page_token = ... # type: typing___Text

    @property
    def operation_filter(self) -> global___OperationFilter: ...

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        filter : typing___Optional[typing___Text] = None,
        page_size : typing___Optional[builtin___int] = None,
        page_token : typing___Optional[typing___Text] = None,
        operation_filter : typing___Optional[global___OperationFilter] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ListOperationsRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ListOperationsRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"operation_filter",b"operation_filter"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"filter",b"filter",u"name",b"name",u"operation_filter",b"operation_filter",u"page_size",b"page_size",u"page_token",b"page_token"]) -> None: ...
global___ListOperationsRequest = ListOperationsRequest

class OperationFilter(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    project_parents = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]
    statuses = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[ondewo___nlu___operation_metadata_pb2___OperationMetadata.Status]
    types = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[ondewo___nlu___operation_metadata_pb2___OperationMetadata.OperationType]
    user_ids = ... # type: google___protobuf___internal___containers___RepeatedScalarFieldContainer[typing___Text]

    @property
    def start_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    @property
    def end_time(self) -> google___protobuf___timestamp_pb2___Timestamp: ...

    def __init__(self,
        *,
        project_parents : typing___Optional[typing___Iterable[typing___Text]] = None,
        statuses : typing___Optional[typing___Iterable[ondewo___nlu___operation_metadata_pb2___OperationMetadata.Status]] = None,
        types : typing___Optional[typing___Iterable[ondewo___nlu___operation_metadata_pb2___OperationMetadata.OperationType]] = None,
        start_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        end_time : typing___Optional[google___protobuf___timestamp_pb2___Timestamp] = None,
        user_ids : typing___Optional[typing___Iterable[typing___Text]] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> OperationFilter: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> OperationFilter: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"end_time",b"end_time",u"start_time",b"start_time"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"end_time",b"end_time",u"project_parents",b"project_parents",u"start_time",b"start_time",u"statuses",b"statuses",u"types",b"types",u"user_ids",b"user_ids"]) -> None: ...
global___OperationFilter = OperationFilter

class ListOperationsResponse(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    next_page_token = ... # type: typing___Text

    @property
    def operations(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[global___Operation]: ...

    def __init__(self,
        *,
        operations : typing___Optional[typing___Iterable[global___Operation]] = None,
        next_page_token : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> ListOperationsResponse: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> ListOperationsResponse: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"next_page_token",b"next_page_token",u"operations",b"operations"]) -> None: ...
global___ListOperationsResponse = ListOperationsResponse

class CancelOperationRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> CancelOperationRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> CancelOperationRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name"]) -> None: ...
global___CancelOperationRequest = CancelOperationRequest

class DeleteOperationRequest(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name = ... # type: typing___Text

    def __init__(self,
        *,
        name : typing___Optional[typing___Text] = None,
        ) -> None: ...
    if sys.version_info >= (3,):
        @classmethod
        def FromString(cls, s: builtin___bytes) -> DeleteOperationRequest: ...
    else:
        @classmethod
        def FromString(cls, s: typing___Union[builtin___bytes, builtin___buffer, builtin___unicode]) -> DeleteOperationRequest: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"name",b"name"]) -> None: ...
global___DeleteOperationRequest = DeleteOperationRequest
