"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2020-2026 ONDEWO GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.rpc.status_pb2
import ondewo.nlu.common_pb2
import ondewo.nlu.operation_metadata_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _RemoteOperationContainerLifecycleState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _RemoteOperationContainerLifecycleStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RemoteOperationContainerLifecycleState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_UNSPECIFIED: _RemoteOperationContainerLifecycleState.ValueType  # 0
    """The lifecycle state could not be determined."""
    REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_NOT_FOUND: _RemoteOperationContainerLifecycleState.ValueType  # 1
    """No container with the recorded name exists on the recorded host (never started, already reaped,
    or the dispatch record was garbage-collected after completion).
    """
    REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_CREATED: _RemoteOperationContainerLifecycleState.ValueType  # 2
    """The container has been created but is not yet running."""
    REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RUNNING: _RemoteOperationContainerLifecycleState.ValueType  # 3
    """The container is running."""
    REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_PAUSED: _RemoteOperationContainerLifecycleState.ValueType  # 4
    """The container is paused."""
    REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RESTARTING: _RemoteOperationContainerLifecycleState.ValueType  # 5
    """The container is in the process of restarting."""
    REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_EXITED: _RemoteOperationContainerLifecycleState.ValueType  # 6
    """The container has exited (successfully or with an error — see <code>exit_code</code>)."""
    REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_DEAD: _RemoteOperationContainerLifecycleState.ValueType  # 7
    """The container is dead (Docker could not stop/remove it cleanly)."""

class RemoteOperationContainerLifecycleState(_RemoteOperationContainerLifecycleState, metaclass=_RemoteOperationContainerLifecycleStateEnumTypeWrapper):
    """The lifecycle state of a remote-operation container, mirroring the Docker container lifecycle."""

REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_UNSPECIFIED: RemoteOperationContainerLifecycleState.ValueType  # 0
"""The lifecycle state could not be determined."""
REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_NOT_FOUND: RemoteOperationContainerLifecycleState.ValueType  # 1
"""No container with the recorded name exists on the recorded host (never started, already reaped,
or the dispatch record was garbage-collected after completion).
"""
REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_CREATED: RemoteOperationContainerLifecycleState.ValueType  # 2
"""The container has been created but is not yet running."""
REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RUNNING: RemoteOperationContainerLifecycleState.ValueType  # 3
"""The container is running."""
REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_PAUSED: RemoteOperationContainerLifecycleState.ValueType  # 4
"""The container is paused."""
REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_RESTARTING: RemoteOperationContainerLifecycleState.ValueType  # 5
"""The container is in the process of restarting."""
REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_EXITED: RemoteOperationContainerLifecycleState.ValueType  # 6
"""The container has exited (successfully or with an error — see <code>exit_code</code>)."""
REMOTE_OPERATION_CONTAINER_LIFECYCLE_STATE_DEAD: RemoteOperationContainerLifecycleState.ValueType  # 7
"""The container is dead (Docker could not stop/remove it cleanly)."""
global___RemoteOperationContainerLifecycleState = RemoteOperationContainerLifecycleState

@typing.final
class Operation(google.protobuf.message.Message):
    """This resource represents a long-running operation that is the result of a network API call."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    DONE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    RESPONSE_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The server-assigned name, which is only unique within the same service that
    originally returns it. If you use the default HTTP mapping, the
    <code>name</code> should have the format of <code>operations/some/unique/name</code>.
    """
    done: builtins.bool
    """If the value is <code>false</code>, it means the operation is still in progress.
    If true, the operation is completed, and either <code>error</code> or <code>response</code> is
    available.
    """
    @property
    def metadata(self) -> ondewo.nlu.operation_metadata_pb2.OperationMetadata:
        """Service-specific metadata associated with the operation.  It typically
        contains progress information and common metadata such as create time.
        Some services might not provide such metadata.  Any method that returns a
        long-running operation should document the metadata type, if any.
        """

    @property
    def error(self) -> google.rpc.status_pb2.Status:
        """The error result of the operation in case of failure or cancellation."""

    @property
    def response(self) -> google.protobuf.any_pb2.Any:
        """The normal response of the operation in case of success.  If the original
        method returns no data on success, such as <code>Delete</code>, the response is
        <code>google.protobuf.Empty</code>.  If the original method is standard
        <code>Get</code>/<code>Create</code>/<code>Update</code>, the response should be the resource.  For other
        methods, the response should have the type <code>XxxResponse</code>, where <code>Xxx</code>
        is the original method name.  For example, if the original method name
        is <code>TakeSnapshot()</code>, the inferred response type is
        <code>TakeSnapshotResponse</code>.
        """

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        metadata: ondewo.nlu.operation_metadata_pb2.OperationMetadata | None = ...,
        done: builtins.bool = ...,
        error: google.rpc.status_pb2.Status | None = ...,
        response: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "metadata", b"metadata", "response", b"response", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["done", b"done", "error", b"error", "metadata", b"metadata", "name", b"name", "response", b"response", "result", b"result"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["result", b"result"]) -> typing.Literal["error", "response"] | None: ...

global___Operation = Operation

@typing.final
class GetOperationRequest(google.protobuf.message.Message):
    """The request message for <a href="index.html#ondewo.nlu.Operations.GetOperation">Operations.GetOperation</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    FIELD_MASK_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the operation resource."""
    @property
    def field_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Optional. The mask to control which fields gets returned."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        field_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_field_mask", b"_field_mask", "field_mask", b"field_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_field_mask", b"_field_mask", "field_mask", b"field_mask", "name", b"name"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_field_mask", b"_field_mask"]) -> typing.Literal["field_mask"] | None: ...

global___GetOperationRequest = GetOperationRequest

@typing.final
class ListOperationsRequest(google.protobuf.message.Message):
    """The request message for <a href="index.html#ondewo.nlu.Operations.ListOperations">Operations.ListOperations</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    OPERATION_FILTER_FIELD_NUMBER: builtins.int
    FIELD_MASK_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the operation collection."""
    filter: builtins.str
    """The standard list filter."""
    page_size: builtins.int
    """The standard list page size."""
    page_token: builtins.str
    """Optional: The page token to support pagination.
    Pagination allows you to retrieve a large result set in smaller, more manageable portions.
    The page token is a string representing the current index and page size.

    Valid page token strings:
    <ul>
      <li>&quot;&quot; (empty string) - Retrieves the first page.</li>
      <li>&quot;current_index-0--page_size-20&quot; - Retrieves the first page with a page size of 20.</li>
      <li>&quot;current_index-1--page_size-20&quot; - Retrieves the second page with a page size of 20.</li>
    </ul>

    Index starts at 0.

    Examples of valid page token strings:
    <ul>
      <li>&quot;&quot;</li>
      <li>&quot;current_index-0--page_size-20&quot;</li>
      <li>&quot;current_index-1--page_size-20&quot;</li>
      <li>&quot;current_index-10--page_size-20&quot;</li>
    </ul>

    Examples of invalid page token strings:
    <ul>
      <li>&quot;1&quot;</li>
      <li>&quot;current_index-0--page_size-20&quot;</li>
      <li>&quot;current_index--1--page_size-20&quot;</li>
      <li>&quot;current_index1--page_size-20&quot;</li>
      <li>&quot;current_index-1--page_size--20&quot;</li>
    </ul>
    """
    @property
    def operation_filter(self) -> global___OperationFilter:
        """Optional. A filter to narrow the response down to operations of interest."""

    @property
    def field_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Optional. The mask to control which fields gets returned."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        filter: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        operation_filter: global___OperationFilter | None = ...,
        field_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_field_mask", b"_field_mask", "field_mask", b"field_mask", "operation_filter", b"operation_filter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_field_mask", b"_field_mask", "field_mask", b"field_mask", "filter", b"filter", "name", b"name", "operation_filter", b"operation_filter", "page_size", b"page_size", "page_token", b"page_token"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_field_mask", b"_field_mask"]) -> typing.Literal["field_mask"] | None: ...

global___ListOperationsRequest = ListOperationsRequest

@typing.final
class OperationFilter(google.protobuf.message.Message):
    """This message contains an operation filter"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_PARENTS_FIELD_NUMBER: builtins.int
    STATUSES_FIELD_NUMBER: builtins.int
    TYPES_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    USER_IDS_FIELD_NUMBER: builtins.int
    @property
    def project_parents(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """An operationFilter can be used in some requests to return only operations matching certain filter conditions.

        All fields below are  optional. Multiple fields specified at the same time are chained via OR.
        Match operations with any of the following project parents.
        """

    @property
    def statuses(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[ondewo.nlu.operation_metadata_pb2.OperationMetadata.Status.ValueType]:
        """Match operation which had any of the following operation statuses."""

    @property
    def types(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[ondewo.nlu.operation_metadata_pb2.OperationMetadata.OperationType.ValueType]:
        """Match operation which had any of the following operation types."""

    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The time operation processing started."""

    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The time operation processing completed."""

    @property
    def user_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Match operation which had any of the following user_ids."""

    def __init__(
        self,
        *,
        project_parents: collections.abc.Iterable[builtins.str] | None = ...,
        statuses: collections.abc.Iterable[ondewo.nlu.operation_metadata_pb2.OperationMetadata.Status.ValueType] | None = ...,
        types: collections.abc.Iterable[ondewo.nlu.operation_metadata_pb2.OperationMetadata.OperationType.ValueType] | None = ...,
        start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        user_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end_time", b"end_time", "end_time_oneof", b"end_time_oneof", "start_time", b"start_time", "start_time_oneof", b"start_time_oneof"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["end_time", b"end_time", "end_time_oneof", b"end_time_oneof", "project_parents", b"project_parents", "start_time", b"start_time", "start_time_oneof", b"start_time_oneof", "statuses", b"statuses", "types", b"types", "user_ids", b"user_ids"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["end_time_oneof", b"end_time_oneof"]) -> typing.Literal["end_time"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["start_time_oneof", b"start_time_oneof"]) -> typing.Literal["start_time"] | None: ...

global___OperationFilter = OperationFilter

@typing.final
class ListOperationsResponse(google.protobuf.message.Message):
    """The response message for <a href="index.html#ondewo.nlu.Operations.ListOperations">Operations.ListOperations</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATIONS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """The next_page_token is used to retrieve the next page of a returned result,
    e.g. next_page_token is current_index-2
    """
    @property
    def operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Operation]:
        """A list of operations that matches the specified filter in the request."""

    def __init__(
        self,
        *,
        operations: collections.abc.Iterable[global___Operation] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "operations", b"operations"]) -> None: ...

global___ListOperationsResponse = ListOperationsResponse

@typing.final
class CancelOperationRequest(google.protobuf.message.Message):
    """The request message for <a href="index.html#ondewo.nlu.Operations.CancelOperation">Operations.CancelOperation</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the operation resource to be cancelled."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___CancelOperationRequest = CancelOperationRequest

@typing.final
class DeleteOperationRequest(google.protobuf.message.Message):
    """The request message for <a href="index.html#ondewo.nlu.Operations.DeleteOperation">Operations.DeleteOperation</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the operation resource to be deleted."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___DeleteOperationRequest = DeleteOperationRequest

@typing.final
class StreamRemoteOperationContainerLogsRequest(google.protobuf.message.Message):
    """The request message for <a href="index.html#ondewo.nlu.Operations.StreamRemoteOperationContainerLogs">Operations.StreamRemoteOperationContainerLogs</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    MIN_LOG_LEVEL_FIELD_NUMBER: builtins.int
    TAIL_LINES_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the operation resource whose container logs should be streamed."""
    min_log_level: ondewo.nlu.common_pb2.LogSeverity.ValueType
    """Only stream lines at or above this loguru severity. <code>LOG_SEVERITY_UNSPECIFIED</code> (the
    default) streams every line regardless of level.
    """
    tail_lines: builtins.int
    """Replay at most this many of the most recent existing log lines before switching to live follow.
    <code>0</code> (the default) starts the follow with no historical replay.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        min_log_level: ondewo.nlu.common_pb2.LogSeverity.ValueType = ...,
        tail_lines: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["min_log_level", b"min_log_level", "name", b"name", "tail_lines", b"tail_lines"]) -> None: ...

global___StreamRemoteOperationContainerLogsRequest = StreamRemoteOperationContainerLogsRequest

@typing.final
class GetRemoteOperationContainerLogsRequest(google.protobuf.message.Message):
    """The request message for <a href="index.html#ondewo.nlu.Operations.GetRemoteOperationContainerLogs">Operations.GetRemoteOperationContainerLogs</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    MIN_LOG_LEVEL_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    MAX_LINES_FIELD_NUMBER: builtins.int
    REGEX_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the operation resource whose container logs should be returned."""
    min_log_level: ondewo.nlu.common_pb2.LogSeverity.ValueType
    """Only return lines at or above this loguru severity. <code>LOG_SEVERITY_UNSPECIFIED</code> (the
    default) returns every line regardless of level.
    """
    max_lines: builtins.int
    """Return at most this many lines, keeping the most recent matches. <code>0</code> (the default)
    applies a server-side safety cap.
    """
    regex: builtins.str
    """Only return lines whose message matches this regular expression (Python <code>re</code> syntax).
    Empty (the default) disables regex filtering.
    """
    @property
    def start_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Only return lines whose timestamp is at or after this instant. Unset returns from the start of
        the available logs.
        """

    @property
    def end_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Only return lines whose timestamp is at or before this instant. Unset returns up to the latest
        available log line.
        """

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        min_log_level: ondewo.nlu.common_pb2.LogSeverity.ValueType = ...,
        start_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        max_lines: builtins.int = ...,
        regex: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end_time", b"end_time", "start_time", b"start_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["end_time", b"end_time", "max_lines", b"max_lines", "min_log_level", b"min_log_level", "name", b"name", "regex", b"regex", "start_time", b"start_time"]) -> None: ...

global___GetRemoteOperationContainerLogsRequest = GetRemoteOperationContainerLogsRequest

@typing.final
class GetRemoteOperationContainerLogsResponse(google.protobuf.message.Message):
    """The response message for <a href="index.html#ondewo.nlu.Operations.GetRemoteOperationContainerLogs">Operations.GetRemoteOperationContainerLogs</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOG_LINES_FIELD_NUMBER: builtins.int
    TRUNCATED_FIELD_NUMBER: builtins.int
    truncated: builtins.bool
    """True when older matching lines were dropped because <code>max_lines</code> was reached."""
    @property
    def log_lines(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RemoteOperationContainerLogLine]:
        """The matching log lines, oldest first. Secrets are redacted server-side."""

    def __init__(
        self,
        *,
        log_lines: collections.abc.Iterable[global___RemoteOperationContainerLogLine] | None = ...,
        truncated: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["log_lines", b"log_lines", "truncated", b"truncated"]) -> None: ...

global___GetRemoteOperationContainerLogsResponse = GetRemoteOperationContainerLogsResponse

@typing.final
class RemoteOperationContainerLogLine(google.protobuf.message.Message):
    """A single parsed container log line, emitted by both the streaming and the query RPCs."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    LEVEL_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    level: ondewo.nlu.common_pb2.LogSeverity.ValueType
    """The loguru severity parsed from the line, or <code>LOG_SEVERITY_UNSPECIFIED</code> if the line
    carried no recognizable level (e.g. a continuation / traceback line).
    """
    message: builtins.str
    """The log message text, with ANSI colour codes stripped and secrets redacted."""
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The timestamp parsed from the loguru line prefix, if present."""

    def __init__(
        self,
        *,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        level: ondewo.nlu.common_pb2.LogSeverity.ValueType = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["level", b"level", "message", b"message", "timestamp", b"timestamp"]) -> None: ...

global___RemoteOperationContainerLogLine = RemoteOperationContainerLogLine

@typing.final
class GetRemoteOperationContainerStatusRequest(google.protobuf.message.Message):
    """The request message for <a href="index.html#ondewo.nlu.Operations.GetRemoteOperationContainerStatus">Operations.GetRemoteOperationContainerStatus</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the operation resource whose container status should be returned."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetRemoteOperationContainerStatusRequest = GetRemoteOperationContainerStatusRequest

@typing.final
class RemoteOperationContainerStatus(google.protobuf.message.Message):
    """The response message for <a href="index.html#ondewo.nlu.Operations.GetRemoteOperationContainerStatus">Operations.GetRemoteOperationContainerStatus</a>."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    LIFECYCLE_STATE_FIELD_NUMBER: builtins.int
    HOST_NAME_FIELD_NUMBER: builtins.int
    CONTAINER_NAME_FIELD_NUMBER: builtins.int
    EXIT_CODE_FIELD_NUMBER: builtins.int
    OOM_KILLED_FIELD_NUMBER: builtins.int
    HEALTH_STATUS_FIELD_NUMBER: builtins.int
    STARTED_AT_FIELD_NUMBER: builtins.int
    FINISHED_AT_FIELD_NUMBER: builtins.int
    OBSERVED_AT_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the operation resource this status describes."""
    lifecycle_state: global___RemoteOperationContainerLifecycleState.ValueType
    """The lifecycle state of the container."""
    host_name: builtins.str
    """The host the container was dispatched to (empty when the dispatch record is unavailable)."""
    container_name: builtins.str
    """The container name (empty when the dispatch record is unavailable)."""
    exit_code: builtins.int
    """The container exit code. Only meaningful when <code>lifecycle_state</code> is
    <code>EXITED</code> or <code>DEAD</code>.
    """
    oom_killed: builtins.bool
    """True when the container was killed by the out-of-memory killer."""
    health_status: builtins.str
    """The Docker healthcheck status (<code>healthy</code> / <code>unhealthy</code> / <code>starting</code>),
    empty when the container declares no healthcheck.
    """
    @property
    def started_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """When the container started, if known."""

    @property
    def finished_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """When the container finished, if it has exited."""

    @property
    def observed_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """When this status was observed by the server."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        lifecycle_state: global___RemoteOperationContainerLifecycleState.ValueType = ...,
        host_name: builtins.str = ...,
        container_name: builtins.str = ...,
        exit_code: builtins.int = ...,
        oom_killed: builtins.bool = ...,
        health_status: builtins.str = ...,
        started_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        finished_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        observed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["finished_at", b"finished_at", "observed_at", b"observed_at", "started_at", b"started_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["container_name", b"container_name", "exit_code", b"exit_code", "finished_at", b"finished_at", "health_status", b"health_status", "host_name", b"host_name", "lifecycle_state", b"lifecycle_state", "name", b"name", "observed_at", b"observed_at", "oom_killed", b"oom_killed", "started_at", b"started_at"]) -> None: ...

global___RemoteOperationContainerStatus = RemoteOperationContainerStatus
