# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from ondewo.nlu.ccai_project_pb2 import (
    CcaiProject,
    CcaiService,
    CreateCcaiProjectRequest,
    CreateCcaiProjectResponse,
    DeleteCcaiProjectRequest,
    DeleteCcaiProjectResponse,
    GetCcaiProjectRequest,
    GetCcaiServiceRequest,
    ListCcaiProjectsRequest,
    ListCcaiProjectsResponse,
    UpdateCcaiProjectRequest,
    UpdateCcaiProjectResponse,
)
from ondewo.nlu.ccai_project_pb2_grpc import CcaiProjectsStub
from ondewo.nlu.core.async_services_interface import AsyncServicesInterface


class CcaiProjects(AsyncServicesInterface):
    """
    Exposes the CcaiProjects-related endpoints of ONDEWO NLU services in a user-friendly way.

    See ccai_project.proto.
    """

    @property
    def stub(self) -> CcaiProjectsStub:
        stub: CcaiProjectsStub = CcaiProjectsStub(channel=self.grpc_channel)
        return stub

    async def get_ccai_project(self, request: GetCcaiProjectRequest) -> CcaiProject:
        response: CcaiProject = await self.stub.GetCcaiProject(request, metadata=self.metadata)
        return response

    async def create_ccai_project(self, request: CreateCcaiProjectRequest) -> CreateCcaiProjectResponse:
        response: CreateCcaiProjectResponse = await self.stub.CreateCcaiProject(request, metadata=self.metadata)
        return response

    async def delete_ccai_project(self, request: DeleteCcaiProjectRequest) -> DeleteCcaiProjectResponse:
        response: DeleteCcaiProjectResponse = await self.stub.DeleteCcaiProject(request, metadata=self.metadata)
        return response

    async def list_ccai_projects(self, request: ListCcaiProjectsRequest) -> ListCcaiProjectsResponse:
        response: ListCcaiProjectsResponse = await self.stub.ListCcaiProjects(request, metadata=self.metadata)
        return response

    async def update_ccai_project(self, request: UpdateCcaiProjectRequest) -> UpdateCcaiProjectResponse:
        response: UpdateCcaiProjectResponse = await self.stub.UpdateCcaiProject(request, metadata=self.metadata)
        return response

    async def get_ccai_service(self, request: GetCcaiServiceRequest) -> CcaiService:
        response: CcaiService = await self.stub.GetCcaiService(request, metadata=self.metadata)
        return response
