# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from typing import AsyncIterator

from google.protobuf.empty_pb2 import Empty

from ondewo.nlu.operations_pb2 import (
    CancelOperationRequest,
    DeleteOperationRequest,
    GetOperationRequest,
    GetRemoteOperationContainerLogsRequest,
    GetRemoteOperationContainerLogsResponse,
    GetRemoteOperationContainerStatusRequest,
    ListOperationsRequest,
    ListOperationsResponse,
    Operation,
    RemoteOperationContainerLogLine,
    RemoteOperationContainerStatus,
    StreamRemoteOperationContainerLogsRequest,
)
from ondewo.nlu.operations_pb2_grpc import OperationsStub
from ondewo.nlu.core.async_services_interface import AsyncServicesInterface


class Operations(AsyncServicesInterface):
    """
    Exposes the Operations-related endpoints of ONDEWO NLU services in a user-friendly way.

    See operations.proto.
    """

    @property
    def stub(self) -> OperationsStub:
        stub: OperationsStub = OperationsStub(channel=self.grpc_channel)
        return stub

    async def list_operations(self, request: ListOperationsRequest) -> ListOperationsResponse:
        response: ListOperationsResponse = await self.stub.ListOperations(request, metadata=self.metadata)
        return response

    async def get_operation(self, request: GetOperationRequest) -> Operation:
        response: Operation = await self.stub.GetOperation(request, metadata=self.metadata)
        return response

    async def delete_operation(self, request: DeleteOperationRequest) -> Empty:
        response: Empty = await self.stub.DeleteOperation(request, metadata=self.metadata)
        return response

    async def cancel_operation(self, request: CancelOperationRequest) -> Empty:
        response: Empty = await self.stub.CancelOperation(request, metadata=self.metadata)
        return response

    async def stream_remote_operation_container_logs(
        self,
        request: StreamRemoteOperationContainerLogsRequest,
    ) -> AsyncIterator[RemoteOperationContainerLogLine]:
        response: AsyncIterator[RemoteOperationContainerLogLine] = self.stub.StreamRemoteOperationContainerLogs(
            request, metadata=self.metadata
        )
        return response

    async def get_remote_operation_container_logs(
        self,
        request: GetRemoteOperationContainerLogsRequest,
    ) -> GetRemoteOperationContainerLogsResponse:
        response: GetRemoteOperationContainerLogsResponse = await self.stub.GetRemoteOperationContainerLogs(
            request, metadata=self.metadata
        )
        return response

    async def get_remote_operation_container_status(
        self,
        request: GetRemoteOperationContainerStatusRequest,
    ) -> RemoteOperationContainerStatus:
        response: RemoteOperationContainerStatus = await self.stub.GetRemoteOperationContainerStatus(
            request, metadata=self.metadata
        )
        return response
