# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from typing import AsyncIterator

from ondewo.nlu.rag_pb2 import (
    RagAddCrawlerResultsToDatasetsRequest,
    RagCrawler,
    RagCrawlerResult,
    RagCreateCrawlerRequest,
    RagCreateDatasetRequest,
    RagDataset,
    RagDatasetList,
    RagDeleteCrawlerRequest,
    RagDeleteCrawlerResponse,
    RagDeleteCrawlerRunsRequest,
    RagDeleteCrawlerRunsResponse,
    RagDeleteCrawlersRequest,
    RagDeleteCrawlersResponse,
    RagDeleteDocumentsRequest,
    RagDeleteRequest,
    RagDocument,
    RagDocumentIdsRequest,
    RagDocumentList,
    RagDownloadDocumentRequest,
    RagFileChunk,
    RagGetCrawlerAttachedDatasetsRequest,
    RagGetCrawlerAttachedDatasetsResponse,
    RagGetCrawlerRequest,
    RagGetCrawlerResultRequest,
    RagGetCrawlerResultsRequest,
    RagGetCrawlerResultsResponse,
    RagGetCrawlerRunRequest,
    RagListCrawlerRunsRequest,
    RagListCrawlerRunsResponse,
    RagListCrawlersRequest,
    RagListCrawlersResponse,
    RagListDatasetsRequest,
    RagListDocumentsRequest,
    RagPartialSuccess,
    RagRemoveCrawlerResultsFromDatasetsRequest,
    RagRetrievalRequest,
    RagRetrievalResponse,
    RagStartCrawlerRequest,
    RagStopCrawlerRequest,
    RagStopCrawlerResponse,
    RagUpdateCrawlerRequest,
    RagUpdateDatasetRequest,
    RagUpdateDocumentRequest,
    RagUploadDocumentRequest,
)
from ondewo.nlu.rag_pb2_grpc import RagsStub
from ondewo.nlu.core.async_services_interface import AsyncServicesInterface
from ondewo.nlu.operations_pb2 import Operation


class Rags(AsyncServicesInterface):
    """
    Exposes the Rags-related endpoints of ONDEWO NLU services in a user-friendly way.

    See rag.proto.
    """

    @property
    def stub(self) -> RagsStub:
        stub: RagsStub = RagsStub(channel=self.grpc_channel)
        return stub

    async def rag_create_dataset(self, request: RagCreateDatasetRequest) -> RagDataset:
        response: RagDataset = await self.stub.RagCreateDataset(request, metadata=self.metadata)
        return response

    async def rag_update_dataset(self, request: RagUpdateDatasetRequest) -> RagDataset:
        response: RagDataset = await self.stub.RagUpdateDataset(request, metadata=self.metadata)
        return response

    async def rag_delete_datasets(self, request: RagDeleteRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = await self.stub.RagDeleteDatasets(request, metadata=self.metadata)
        return response

    async def rag_list_datasets(self, request: RagListDatasetsRequest) -> RagDatasetList:
        response: RagDatasetList = await self.stub.RagListDatasets(request, metadata=self.metadata)
        return response

    async def rag_upload_document(self, request: AsyncIterator[RagUploadDocumentRequest]) -> RagDocument:
        response: RagDocument = await self.stub.RagUploadDocument(request, metadata=self.metadata)
        return response

    async def rag_update_document(self, request: RagUpdateDocumentRequest) -> RagDocument:
        response: RagDocument = await self.stub.RagUpdateDocument(request, metadata=self.metadata)
        return response

    async def rag_download_document(self, request: RagDownloadDocumentRequest) -> AsyncIterator[RagFileChunk]:
        response: AsyncIterator[RagFileChunk] = self.stub.RagDownloadDocument(request, metadata=self.metadata)
        return response

    async def rag_list_documents(self, request: RagListDocumentsRequest) -> RagDocumentList:
        response: RagDocumentList = await self.stub.RagListDocuments(request, metadata=self.metadata)
        return response

    async def rag_delete_documents(self, request: RagDeleteDocumentsRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = await self.stub.RagDeleteDocuments(request, metadata=self.metadata)
        return response

    async def rag_retrieval(self, request: RagRetrievalRequest) -> RagRetrievalResponse:
        response: RagRetrievalResponse = await self.stub.RagRetrieval(request, metadata=self.metadata)
        return response

    async def rag_parse_documents(self, request: RagDocumentIdsRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = await self.stub.RagParseDocuments(request, metadata=self.metadata)
        return response

    async def rag_stop_parsing(self, request: RagDocumentIdsRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = await self.stub.RagStopParsing(request, metadata=self.metadata)
        return response

    async def rag_create_crawler(self, request: RagCreateCrawlerRequest) -> RagCrawler:
        response: RagCrawler = await self.stub.RagCreateCrawler(request, metadata=self.metadata)
        return response

    async def rag_get_crawler(self, request: RagGetCrawlerRequest) -> RagCrawler:
        response: RagCrawler = await self.stub.RagGetCrawler(request, metadata=self.metadata)
        return response

    async def rag_list_crawlers(self, request: RagListCrawlersRequest) -> RagListCrawlersResponse:
        response: RagListCrawlersResponse = await self.stub.RagListCrawlers(request, metadata=self.metadata)
        return response

    async def rag_update_crawler(self, request: RagUpdateCrawlerRequest) -> RagCrawler:
        response: RagCrawler = await self.stub.RagUpdateCrawler(request, metadata=self.metadata)
        return response

    async def rag_delete_crawler(self, request: RagDeleteCrawlerRequest) -> RagDeleteCrawlerResponse:
        response: RagDeleteCrawlerResponse = await self.stub.RagDeleteCrawler(request, metadata=self.metadata)
        return response

    async def rag_start_crawler(self, request: RagStartCrawlerRequest) -> Operation:
        response: Operation = await self.stub.RagStartCrawler(request, metadata=self.metadata)
        return response

    async def rag_stop_crawler(self, request: RagStopCrawlerRequest) -> RagStopCrawlerResponse:
        response: RagStopCrawlerResponse = await self.stub.RagStopCrawler(request, metadata=self.metadata)
        return response

    async def rag_get_crawler_run(self, request: RagGetCrawlerRunRequest) -> Operation:
        response: Operation = await self.stub.RagGetCrawlerRun(request, metadata=self.metadata)
        return response

    async def rag_list_crawler_runs(self, request: RagListCrawlerRunsRequest) -> RagListCrawlerRunsResponse:
        response: RagListCrawlerRunsResponse = await self.stub.RagListCrawlerRuns(request, metadata=self.metadata)
        return response

    async def rag_delete_crawler_runs(self, request: RagDeleteCrawlerRunsRequest) -> RagDeleteCrawlerRunsResponse:
        response: RagDeleteCrawlerRunsResponse = await self.stub.RagDeleteCrawlerRuns(request, metadata=self.metadata)
        return response

    async def rag_get_crawler_result(self, request: RagGetCrawlerResultRequest) -> RagCrawlerResult:
        response: RagCrawlerResult = await self.stub.RagGetCrawlerResult(request, metadata=self.metadata)
        return response

    async def rag_get_crawler_results(self, request: RagGetCrawlerResultsRequest) -> RagGetCrawlerResultsResponse:
        response: RagGetCrawlerResultsResponse = await self.stub.RagGetCrawlerResults(request, metadata=self.metadata)
        return response

    async def rag_add_crawler_results_to_datasets(self, request: RagAddCrawlerResultsToDatasetsRequest) -> Operation:
        response: Operation = await self.stub.RagAddCrawlerResultsToDatasets(request, metadata=self.metadata)
        return response

    async def rag_remove_crawler_results_from_datasets(
        self,
        request: RagRemoveCrawlerResultsFromDatasetsRequest,
    ) -> Operation:
        response: Operation = await self.stub.RagRemoveCrawlerResultsFromDatasets(request, metadata=self.metadata)
        return response

    async def rag_get_crawler_attached_datasets(
        self,
        request: RagGetCrawlerAttachedDatasetsRequest,
    ) -> RagGetCrawlerAttachedDatasetsResponse:
        response: RagGetCrawlerAttachedDatasetsResponse = await self.stub.RagGetCrawlerAttachedDatasets(
            request, metadata=self.metadata
        )
        return response

    async def rag_delete_crawlers(self, request: RagDeleteCrawlersRequest) -> RagDeleteCrawlersResponse:
        response: RagDeleteCrawlersResponse = await self.stub.RagDeleteCrawlers(request, metadata=self.metadata)
        return response
