# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from google.protobuf.empty_pb2 import Empty

from ondewo.nlu.webhook_pb2 import (
    CreateSessionEntityTypeRequest,
    DeleteSessionEntityTypeRequest,
    PingRequest,
    PingResponse,
    SessionEntityType,
    UpdateSessionEntityTypeRequest,
    WebhookRequest,
    WebhookResponse,
)
from ondewo.nlu.webhook_pb2_grpc import WebhookStub
from ondewo.nlu.core.async_services_interface import AsyncServicesInterface


class Webhook(AsyncServicesInterface):
    """
    Exposes the Webhook-related endpoints of ONDEWO NLU services in a user-friendly way.

    See webhook.proto.
    """

    @property
    def stub(self) -> WebhookStub:
        stub: WebhookStub = WebhookStub(channel=self.grpc_channel)
        return stub

    async def response_refinement(self, request: WebhookRequest) -> WebhookResponse:
        response: WebhookResponse = await self.stub.ResponseRefinement(request, metadata=self.metadata)
        return response

    async def slot_filling(self, request: WebhookRequest) -> WebhookResponse:
        response: WebhookResponse = await self.stub.SlotFilling(request, metadata=self.metadata)
        return response

    async def ping(self, request: PingRequest) -> PingResponse:
        response: PingResponse = await self.stub.Ping(request, metadata=self.metadata)
        return response

    async def create_session_entity_type(self, request: CreateSessionEntityTypeRequest) -> SessionEntityType:
        response: SessionEntityType = await self.stub.CreateSessionEntityType(request, metadata=self.metadata)
        return response

    async def update_session_entity_type(self, request: UpdateSessionEntityTypeRequest) -> SessionEntityType:
        response: SessionEntityType = await self.stub.UpdateSessionEntityType(request, metadata=self.metadata)
        return response

    async def delete_session_entity_type(self, request: DeleteSessionEntityTypeRequest) -> Empty:
        response: Empty = await self.stub.DeleteSessionEntityType(request, metadata=self.metadata)
        return response
