# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from google.protobuf.empty_pb2 import Empty

from ondewo.nlu.context_pb2 import (
    Context,
    CreateContextRequest,
    DeleteAllContextsRequest,
    DeleteContextRequest,
    GetContextRequest,
    ListContextsRequest,
    ListContextsResponse,
    UpdateContextRequest,
)
from ondewo.nlu.context_pb2_grpc import ContextsStub
from ondewo.nlu.core.services_interface import ServicesInterface


class Contexts(ServicesInterface):
    """
    Exposes the Contexts-related endpoints of ONDEWO NLU services in a user-friendly way.

    See context.proto.
    """

    @property
    def stub(self) -> ContextsStub:
        stub: ContextsStub = ContextsStub(channel=self.grpc_channel)
        return stub

    def list_contexts(self, request: ListContextsRequest) -> ListContextsResponse:
        response: ListContextsResponse = self.stub.ListContexts(request, metadata=self.metadata)
        return response

    def get_context(self, request: GetContextRequest) -> Context:
        response: Context = self.stub.GetContext(request, metadata=self.metadata)
        return response

    def create_context(self, request: CreateContextRequest) -> Context:
        response: Context = self.stub.CreateContext(request, metadata=self.metadata)
        return response

    def update_context(self, request: UpdateContextRequest) -> Context:
        response: Context = self.stub.UpdateContext(request, metadata=self.metadata)
        return response

    def delete_context(self, request: DeleteContextRequest) -> Empty:
        response: Empty = self.stub.DeleteContext(request, metadata=self.metadata)
        return response

    def delete_all_contexts(self, request: DeleteAllContextsRequest) -> Empty:
        response: Empty = self.stub.DeleteAllContexts(request, metadata=self.metadata)
        return response
