# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from google.protobuf.empty_pb2 import Empty

from ondewo.nlu.llm_evaluation_pb2 import (
    AddLlmEvaluationExampleRequest,
    AddLlmEvaluationExamplesRequest,
    AddLlmEvaluationExamplesResponse,
    CancelLlmEvaluationExperimentRequest,
    CompareLlmEvaluationExperimentsRequest,
    CreateLlmEvaluationDatasetRequest,
    DeleteLlmEvaluationDatasetRequest,
    DeleteLlmEvaluationExampleRequest,
    DeleteLlmEvaluationExperimentRequest,
    DeleteLlmEvaluationFeedbackRequest,
    GetLlmEvaluationDatasetRequest,
    GetLlmEvaluationExampleRequest,
    GetLlmEvaluationExperimentRequest,
    ListLlmEvaluationDatasetsRequest,
    ListLlmEvaluationDatasetsResponse,
    ListLlmEvaluationExamplesRequest,
    ListLlmEvaluationExamplesResponse,
    ListLlmEvaluationExperimentsRequest,
    ListLlmEvaluationExperimentsResponse,
    ListLlmEvaluationFeedbackRequest,
    ListLlmEvaluationFeedbackResponse,
    LlmEvaluationComparison,
    LlmEvaluationDataset,
    LlmEvaluationExample,
    LlmEvaluationExperiment,
    LlmEvaluationFeedback,
    RunLlmEvaluationExperimentRequest,
    SubmitLlmEvaluationFeedbackRequest,
    UpdateLlmEvaluationDatasetRequest,
    UpdateLlmEvaluationExampleRequest,
    UpdateLlmEvaluationExperimentRequest,
)
from ondewo.nlu.llm_evaluation_pb2_grpc import LlmEvaluationsStub
from ondewo.nlu.core.services_interface import ServicesInterface
from ondewo.nlu.operations_pb2 import Operation


class LlmEvaluations(ServicesInterface):
    """
    Exposes the LlmEvaluations-related endpoints of ONDEWO NLU services in a user-friendly way.

    See llm_evaluation.proto.
    """

    @property
    def stub(self) -> LlmEvaluationsStub:
        stub: LlmEvaluationsStub = LlmEvaluationsStub(channel=self.grpc_channel)
        return stub

    def llm_evaluation_create_dataset(self, request: CreateLlmEvaluationDatasetRequest) -> LlmEvaluationDataset:
        response: LlmEvaluationDataset = self.stub.LlmEvaluationCreateDataset(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_dataset(self, request: GetLlmEvaluationDatasetRequest) -> LlmEvaluationDataset:
        response: LlmEvaluationDataset = self.stub.LlmEvaluationGetDataset(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_datasets(
        self,
        request: ListLlmEvaluationDatasetsRequest,
    ) -> ListLlmEvaluationDatasetsResponse:
        response: ListLlmEvaluationDatasetsResponse = \
            self.stub.LlmEvaluationListDatasets(request, metadata=self.metadata)
        return response

    def llm_evaluation_update_dataset(self, request: UpdateLlmEvaluationDatasetRequest) -> LlmEvaluationDataset:
        response: LlmEvaluationDataset = self.stub.LlmEvaluationUpdateDataset(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_dataset(self, request: DeleteLlmEvaluationDatasetRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteDataset(request, metadata=self.metadata)
        return response

    def llm_evaluation_add_example(self, request: AddLlmEvaluationExampleRequest) -> LlmEvaluationExample:
        response: LlmEvaluationExample = self.stub.LlmEvaluationAddExample(request, metadata=self.metadata)
        return response

    def llm_evaluation_add_examples(self, request: AddLlmEvaluationExamplesRequest) -> AddLlmEvaluationExamplesResponse:
        response: AddLlmEvaluationExamplesResponse = self.stub.LlmEvaluationAddExamples(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_example(self, request: GetLlmEvaluationExampleRequest) -> LlmEvaluationExample:
        response: LlmEvaluationExample = self.stub.LlmEvaluationGetExample(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_examples(
        self,
        request: ListLlmEvaluationExamplesRequest,
    ) -> ListLlmEvaluationExamplesResponse:
        response: ListLlmEvaluationExamplesResponse = \
            self.stub.LlmEvaluationListExamples(request, metadata=self.metadata)
        return response

    def llm_evaluation_update_example(self, request: UpdateLlmEvaluationExampleRequest) -> LlmEvaluationExample:
        response: LlmEvaluationExample = self.stub.LlmEvaluationUpdateExample(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_example(self, request: DeleteLlmEvaluationExampleRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteExample(request, metadata=self.metadata)
        return response

    def llm_evaluation_run_experiment(self, request: RunLlmEvaluationExperimentRequest) -> Operation:
        response: Operation = self.stub.LlmEvaluationRunExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_experiment(self, request: GetLlmEvaluationExperimentRequest) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.LlmEvaluationGetExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_experiments(
        self,
        request: ListLlmEvaluationExperimentsRequest,
    ) -> ListLlmEvaluationExperimentsResponse:
        response: ListLlmEvaluationExperimentsResponse = \
            self.stub.LlmEvaluationListExperiments(request, metadata=self.metadata)
        return response

    def llm_evaluation_update_experiment(
        self,
        request: UpdateLlmEvaluationExperimentRequest,
    ) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.LlmEvaluationUpdateExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_experiment(self, request: DeleteLlmEvaluationExperimentRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_cancel_experiment(
        self,
        request: CancelLlmEvaluationExperimentRequest,
    ) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.LlmEvaluationCancelExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_compare_experiments(
        self,
        request: CompareLlmEvaluationExperimentsRequest,
    ) -> LlmEvaluationComparison:
        response: LlmEvaluationComparison = self.stub.LlmEvaluationCompareExperiments(request, metadata=self.metadata)
        return response

    def llm_evaluation_submit_feedback(self, request: SubmitLlmEvaluationFeedbackRequest) -> LlmEvaluationFeedback:
        response: LlmEvaluationFeedback = self.stub.LlmEvaluationSubmitFeedback(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_feedback(
        self,
        request: ListLlmEvaluationFeedbackRequest,
    ) -> ListLlmEvaluationFeedbackResponse:
        response: ListLlmEvaluationFeedbackResponse = \
            self.stub.LlmEvaluationListFeedback(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_feedback(self, request: DeleteLlmEvaluationFeedbackRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteFeedback(request, metadata=self.metadata)
        return response
