# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from google.protobuf.empty_pb2 import Empty

from ondewo.nlu.llm_evaluation_pb2 import (
    AddLlmEvaluationExampleRequest,
    AddLlmEvaluationExamplesRequest,
    AddLlmEvaluationExamplesResponse,
    ApplyLlmEvaluationAbRolloutRequest,
    CancelLlmEvaluationExperimentRequest,
    CompareLlmEvaluationExperimentsRequest,
    CreateLlmEvaluationAbExperimentRequest,
    CreateLlmEvaluationDatasetRequest,
    CreateLlmEvaluationExamplesFromSessionRequest,
    CreateLlmEvaluationExamplesFromSessionResponse,
    CreateLlmEvaluationOnlineConfigRequest,
    CreateLlmEvaluationReleaseGateRequest,
    CreateLlmEvaluationReportRequest,
    CreateLlmEvaluationScheduleRequest,
    CreateLlmEvaluationScorecardRequest,
    DeleteLlmEvaluationAbExperimentRequest,
    DeleteLlmEvaluationDatasetRequest,
    DeleteLlmEvaluationExampleRequest,
    DeleteLlmEvaluationExperimentRequest,
    DeleteLlmEvaluationFeedbackRequest,
    DeleteLlmEvaluationOnlineConfigRequest,
    DeleteLlmEvaluationReleaseGateRequest,
    DeleteLlmEvaluationReportRequest,
    DeleteLlmEvaluationScheduleRequest,
    DeleteLlmEvaluationScorecardRequest,
    GetLlmEvaluationAbExperimentRequest,
    GetLlmEvaluationAbExperimentResultsRequest,
    GetLlmEvaluationAbExperimentResultsResponse,
    GetLlmEvaluationAbRolloutDecisionRequest,
    GetLlmEvaluationAbRolloutRecommendationRequest,
    GetLlmEvaluationAnnotationQueueItemRequest,
    GetLlmEvaluationDatasetRequest,
    GetLlmEvaluationExampleRequest,
    GetLlmEvaluationExperimentRequest,
    GetLlmEvaluationOnlineConfigRequest,
    GetLlmEvaluationOnlineResultRequest,
    GetLlmEvaluationProjectSettingsRequest,
    GetLlmEvaluationReleaseGateRequest,
    GetLlmEvaluationReleaseGateRunRequest,
    GetLlmEvaluationReportRequest,
    GetLlmEvaluationScheduleRequest,
    GetLlmEvaluationScorecardRequest,
    ListLlmEvaluationAbExperimentsRequest,
    ListLlmEvaluationAbExperimentsResponse,
    ListLlmEvaluationAbRolloutDecisionsRequest,
    ListLlmEvaluationAbRolloutDecisionsResponse,
    ListLlmEvaluationAnnotationQueueItemsRequest,
    ListLlmEvaluationAnnotationQueueItemsResponse,
    ListLlmEvaluationDatasetsRequest,
    ListLlmEvaluationDatasetsResponse,
    ListLlmEvaluationEvaluatorsRequest,
    ListLlmEvaluationEvaluatorsResponse,
    ListLlmEvaluationExamplesRequest,
    ListLlmEvaluationExamplesResponse,
    ListLlmEvaluationExperimentsRequest,
    ListLlmEvaluationExperimentsResponse,
    ListLlmEvaluationFeedbackRequest,
    ListLlmEvaluationFeedbackResponse,
    ListLlmEvaluationOnlineConfigsRequest,
    ListLlmEvaluationOnlineConfigsResponse,
    ListLlmEvaluationOnlineResultsRequest,
    ListLlmEvaluationOnlineResultsResponse,
    ListLlmEvaluationReleaseGateRunsRequest,
    ListLlmEvaluationReleaseGateRunsResponse,
    ListLlmEvaluationReleaseGatesRequest,
    ListLlmEvaluationReleaseGatesResponse,
    ListLlmEvaluationReportsRequest,
    ListLlmEvaluationReportsResponse,
    ListLlmEvaluationSchedulesRequest,
    ListLlmEvaluationSchedulesResponse,
    ListLlmEvaluationScorecardsRequest,
    ListLlmEvaluationScorecardsResponse,
    LlmEvaluationAbExperiment,
    LlmEvaluationAbRolloutDecision,
    LlmEvaluationAbRolloutRecommendation,
    LlmEvaluationAnnotationQueueItem,
    LlmEvaluationComparison,
    LlmEvaluationDataset,
    LlmEvaluationExample,
    LlmEvaluationExperiment,
    LlmEvaluationFeedback,
    LlmEvaluationOnlineConfig,
    LlmEvaluationOnlineResult,
    LlmEvaluationProjectSettings,
    LlmEvaluationReleaseGate,
    LlmEvaluationReleaseGateRun,
    LlmEvaluationReport,
    LlmEvaluationSchedule,
    LlmEvaluationScorecard,
    PromoteLlmEvaluationAnnotationQueueItemRequest,
    PromoteLlmEvaluationAnnotationQueueItemResponse,
    RunLlmEvaluationExperimentRequest,
    RunLlmEvaluationReleaseGateRequest,
    SimulateLlmEvaluationConversationsRequest,
    StartLlmEvaluationAbExperimentRequest,
    StopLlmEvaluationAbExperimentRequest,
    SubmitLlmEvaluationFeedbackRequest,
    UpdateLlmEvaluationAbExperimentRequest,
    UpdateLlmEvaluationAnnotationQueueItemRequest,
    UpdateLlmEvaluationDatasetRequest,
    UpdateLlmEvaluationExampleRequest,
    UpdateLlmEvaluationExperimentRequest,
    UpdateLlmEvaluationFeedbackRequest,
    UpdateLlmEvaluationOnlineConfigRequest,
    UpdateLlmEvaluationProjectSettingsRequest,
    UpdateLlmEvaluationReleaseGateRequest,
    UpdateLlmEvaluationScheduleRequest,
    UpdateLlmEvaluationScorecardRequest,
)
from ondewo.nlu.llm_evaluation_pb2_grpc import LlmEvaluationsStub
from ondewo.nlu.core.services_interface import ServicesInterface
from ondewo.nlu.operations_pb2 import Operation


class LlmEvaluations(ServicesInterface):
    """
    Exposes the LlmEvaluations-related endpoints of ONDEWO NLU services in a user-friendly way.

    See llm_evaluation.proto.
    """

    @property
    def stub(self) -> LlmEvaluationsStub:
        stub: LlmEvaluationsStub = LlmEvaluationsStub(channel=self.grpc_channel)
        return stub

    def llm_evaluation_create_dataset(self, request: CreateLlmEvaluationDatasetRequest) -> LlmEvaluationDataset:
        response: LlmEvaluationDataset = self.stub.LlmEvaluationCreateDataset(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_dataset(self, request: GetLlmEvaluationDatasetRequest) -> LlmEvaluationDataset:
        response: LlmEvaluationDataset = self.stub.LlmEvaluationGetDataset(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_datasets(
        self,
        request: ListLlmEvaluationDatasetsRequest,
    ) -> ListLlmEvaluationDatasetsResponse:
        response: ListLlmEvaluationDatasetsResponse = self.stub.LlmEvaluationListDatasets(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_dataset(self, request: UpdateLlmEvaluationDatasetRequest) -> LlmEvaluationDataset:
        response: LlmEvaluationDataset = self.stub.LlmEvaluationUpdateDataset(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_dataset(self, request: DeleteLlmEvaluationDatasetRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteDataset(request, metadata=self.metadata)
        return response

    def llm_evaluation_add_example(self, request: AddLlmEvaluationExampleRequest) -> LlmEvaluationExample:
        response: LlmEvaluationExample = self.stub.LlmEvaluationAddExample(request, metadata=self.metadata)
        return response

    def llm_evaluation_add_examples(self, request: AddLlmEvaluationExamplesRequest) -> AddLlmEvaluationExamplesResponse:
        response: AddLlmEvaluationExamplesResponse = self.stub.LlmEvaluationAddExamples(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_example(self, request: GetLlmEvaluationExampleRequest) -> LlmEvaluationExample:
        response: LlmEvaluationExample = self.stub.LlmEvaluationGetExample(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_examples(
        self,
        request: ListLlmEvaluationExamplesRequest,
    ) -> ListLlmEvaluationExamplesResponse:
        response: ListLlmEvaluationExamplesResponse = self.stub.LlmEvaluationListExamples(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_example(self, request: UpdateLlmEvaluationExampleRequest) -> LlmEvaluationExample:
        response: LlmEvaluationExample = self.stub.LlmEvaluationUpdateExample(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_example(self, request: DeleteLlmEvaluationExampleRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteExample(request, metadata=self.metadata)
        return response

    def llm_evaluation_run_experiment(self, request: RunLlmEvaluationExperimentRequest) -> Operation:
        response: Operation = self.stub.LlmEvaluationRunExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_experiment(self, request: GetLlmEvaluationExperimentRequest) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.LlmEvaluationGetExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_experiments(
        self,
        request: ListLlmEvaluationExperimentsRequest,
    ) -> ListLlmEvaluationExperimentsResponse:
        response: ListLlmEvaluationExperimentsResponse = self.stub.LlmEvaluationListExperiments(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_experiment(
        self,
        request: UpdateLlmEvaluationExperimentRequest,
    ) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.LlmEvaluationUpdateExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_experiment(self, request: DeleteLlmEvaluationExperimentRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_cancel_experiment(
        self,
        request: CancelLlmEvaluationExperimentRequest,
    ) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.LlmEvaluationCancelExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_compare_experiments(
        self,
        request: CompareLlmEvaluationExperimentsRequest,
    ) -> LlmEvaluationComparison:
        response: LlmEvaluationComparison = self.stub.LlmEvaluationCompareExperiments(request, metadata=self.metadata)
        return response

    def llm_evaluation_submit_feedback(self, request: SubmitLlmEvaluationFeedbackRequest) -> LlmEvaluationFeedback:
        response: LlmEvaluationFeedback = self.stub.LlmEvaluationSubmitFeedback(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_feedback(
        self,
        request: ListLlmEvaluationFeedbackRequest,
    ) -> ListLlmEvaluationFeedbackResponse:
        response: ListLlmEvaluationFeedbackResponse = self.stub.LlmEvaluationListFeedback(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_delete_feedback(self, request: DeleteLlmEvaluationFeedbackRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteFeedback(request, metadata=self.metadata)
        return response

    def llm_evaluation_update_feedback(self, request: UpdateLlmEvaluationFeedbackRequest) -> LlmEvaluationFeedback:
        response: LlmEvaluationFeedback = self.stub.LlmEvaluationUpdateFeedback(request, metadata=self.metadata)
        return response

    def llm_evaluation_create_release_gate(
        self,
        request: CreateLlmEvaluationReleaseGateRequest,
    ) -> LlmEvaluationReleaseGate:
        response: LlmEvaluationReleaseGate = self.stub.LlmEvaluationCreateReleaseGate(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_release_gate(self, request: GetLlmEvaluationReleaseGateRequest) -> LlmEvaluationReleaseGate:
        response: LlmEvaluationReleaseGate = self.stub.LlmEvaluationGetReleaseGate(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_release_gates(
        self,
        request: ListLlmEvaluationReleaseGatesRequest,
    ) -> ListLlmEvaluationReleaseGatesResponse:
        response: ListLlmEvaluationReleaseGatesResponse = self.stub.LlmEvaluationListReleaseGates(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_release_gate(
        self,
        request: UpdateLlmEvaluationReleaseGateRequest,
    ) -> LlmEvaluationReleaseGate:
        response: LlmEvaluationReleaseGate = self.stub.LlmEvaluationUpdateReleaseGate(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_release_gate(self, request: DeleteLlmEvaluationReleaseGateRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteReleaseGate(request, metadata=self.metadata)
        return response

    def llm_evaluation_run_release_gate(self, request: RunLlmEvaluationReleaseGateRequest) -> Operation:
        response: Operation = self.stub.LlmEvaluationRunReleaseGate(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_release_gate_run(
        self,
        request: GetLlmEvaluationReleaseGateRunRequest,
    ) -> LlmEvaluationReleaseGateRun:
        response: LlmEvaluationReleaseGateRun = self.stub.LlmEvaluationGetReleaseGateRun(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_list_release_gate_runs(
        self,
        request: ListLlmEvaluationReleaseGateRunsRequest,
    ) -> ListLlmEvaluationReleaseGateRunsResponse:
        response: ListLlmEvaluationReleaseGateRunsResponse = self.stub.LlmEvaluationListReleaseGateRuns(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_create_scorecard(self, request: CreateLlmEvaluationScorecardRequest) -> LlmEvaluationScorecard:
        response: LlmEvaluationScorecard = self.stub.LlmEvaluationCreateScorecard(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_scorecard(self, request: GetLlmEvaluationScorecardRequest) -> LlmEvaluationScorecard:
        response: LlmEvaluationScorecard = self.stub.LlmEvaluationGetScorecard(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_scorecards(
        self,
        request: ListLlmEvaluationScorecardsRequest,
    ) -> ListLlmEvaluationScorecardsResponse:
        response: ListLlmEvaluationScorecardsResponse = self.stub.LlmEvaluationListScorecards(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_scorecard(self, request: UpdateLlmEvaluationScorecardRequest) -> LlmEvaluationScorecard:
        response: LlmEvaluationScorecard = self.stub.LlmEvaluationUpdateScorecard(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_scorecard(self, request: DeleteLlmEvaluationScorecardRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteScorecard(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_project_settings(
        self,
        request: GetLlmEvaluationProjectSettingsRequest,
    ) -> LlmEvaluationProjectSettings:
        response: LlmEvaluationProjectSettings = self.stub.LlmEvaluationGetProjectSettings(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_project_settings(
        self,
        request: UpdateLlmEvaluationProjectSettingsRequest,
    ) -> LlmEvaluationProjectSettings:
        response: LlmEvaluationProjectSettings = self.stub.LlmEvaluationUpdateProjectSettings(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_list_evaluators(
        self,
        request: ListLlmEvaluationEvaluatorsRequest,
    ) -> ListLlmEvaluationEvaluatorsResponse:
        response: ListLlmEvaluationEvaluatorsResponse = self.stub.LlmEvaluationListEvaluators(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_create_examples_from_session(
        self,
        request: CreateLlmEvaluationExamplesFromSessionRequest,
    ) -> CreateLlmEvaluationExamplesFromSessionResponse:
        response: CreateLlmEvaluationExamplesFromSessionResponse = self.stub.LlmEvaluationCreateExamplesFromSession(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_simulate_conversations(self, request: SimulateLlmEvaluationConversationsRequest) -> Operation:
        response: Operation = self.stub.LlmEvaluationSimulateConversations(request, metadata=self.metadata)
        return response

    def llm_evaluation_create_schedule(self, request: CreateLlmEvaluationScheduleRequest) -> LlmEvaluationSchedule:
        response: LlmEvaluationSchedule = self.stub.LlmEvaluationCreateSchedule(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_schedule(self, request: GetLlmEvaluationScheduleRequest) -> LlmEvaluationSchedule:
        response: LlmEvaluationSchedule = self.stub.LlmEvaluationGetSchedule(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_schedules(
        self,
        request: ListLlmEvaluationSchedulesRequest,
    ) -> ListLlmEvaluationSchedulesResponse:
        response: ListLlmEvaluationSchedulesResponse = self.stub.LlmEvaluationListSchedules(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_schedule(self, request: UpdateLlmEvaluationScheduleRequest) -> LlmEvaluationSchedule:
        response: LlmEvaluationSchedule = self.stub.LlmEvaluationUpdateSchedule(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_schedule(self, request: DeleteLlmEvaluationScheduleRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteSchedule(request, metadata=self.metadata)
        return response

    def llm_evaluation_create_report(self, request: CreateLlmEvaluationReportRequest) -> LlmEvaluationReport:
        response: LlmEvaluationReport = self.stub.LlmEvaluationCreateReport(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_report(self, request: GetLlmEvaluationReportRequest) -> LlmEvaluationReport:
        response: LlmEvaluationReport = self.stub.LlmEvaluationGetReport(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_reports(self, request: ListLlmEvaluationReportsRequest) -> ListLlmEvaluationReportsResponse:
        response: ListLlmEvaluationReportsResponse = self.stub.LlmEvaluationListReports(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_report(self, request: DeleteLlmEvaluationReportRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteReport(request, metadata=self.metadata)
        return response

    def llm_evaluation_create_ab_experiment(
        self,
        request: CreateLlmEvaluationAbExperimentRequest,
    ) -> LlmEvaluationAbExperiment:
        response: LlmEvaluationAbExperiment = self.stub.LlmEvaluationCreateAbExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_ab_experiment(
        self,
        request: GetLlmEvaluationAbExperimentRequest,
    ) -> LlmEvaluationAbExperiment:
        response: LlmEvaluationAbExperiment = self.stub.LlmEvaluationGetAbExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_ab_experiments(
        self,
        request: ListLlmEvaluationAbExperimentsRequest,
    ) -> ListLlmEvaluationAbExperimentsResponse:
        response: ListLlmEvaluationAbExperimentsResponse = self.stub.LlmEvaluationListAbExperiments(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_ab_experiment(
        self,
        request: UpdateLlmEvaluationAbExperimentRequest,
    ) -> LlmEvaluationAbExperiment:
        response: LlmEvaluationAbExperiment = self.stub.LlmEvaluationUpdateAbExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_ab_experiment(self, request: DeleteLlmEvaluationAbExperimentRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteAbExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_start_ab_experiment(
        self,
        request: StartLlmEvaluationAbExperimentRequest,
    ) -> LlmEvaluationAbExperiment:
        response: LlmEvaluationAbExperiment = self.stub.LlmEvaluationStartAbExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_stop_ab_experiment(
        self,
        request: StopLlmEvaluationAbExperimentRequest,
    ) -> LlmEvaluationAbExperiment:
        response: LlmEvaluationAbExperiment = self.stub.LlmEvaluationStopAbExperiment(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_ab_experiment_results(
        self,
        request: GetLlmEvaluationAbExperimentResultsRequest,
    ) -> GetLlmEvaluationAbExperimentResultsResponse:
        response: GetLlmEvaluationAbExperimentResultsResponse = self.stub.LlmEvaluationGetAbExperimentResults(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_get_ab_rollout_recommendation(
        self,
        request: GetLlmEvaluationAbRolloutRecommendationRequest,
    ) -> LlmEvaluationAbRolloutRecommendation:
        response: LlmEvaluationAbRolloutRecommendation = self.stub.LlmEvaluationGetAbRolloutRecommendation(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_apply_ab_rollout(
        self,
        request: ApplyLlmEvaluationAbRolloutRequest,
    ) -> LlmEvaluationAbRolloutDecision:
        response: LlmEvaluationAbRolloutDecision = self.stub.LlmEvaluationApplyAbRollout(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_get_ab_rollout_decision(
        self,
        request: GetLlmEvaluationAbRolloutDecisionRequest,
    ) -> LlmEvaluationAbRolloutDecision:
        response: LlmEvaluationAbRolloutDecision = self.stub.LlmEvaluationGetAbRolloutDecision(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_list_ab_rollout_decisions(
        self,
        request: ListLlmEvaluationAbRolloutDecisionsRequest,
    ) -> ListLlmEvaluationAbRolloutDecisionsResponse:
        response: ListLlmEvaluationAbRolloutDecisionsResponse = self.stub.LlmEvaluationListAbRolloutDecisions(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_create_online_config(
        self,
        request: CreateLlmEvaluationOnlineConfigRequest,
    ) -> LlmEvaluationOnlineConfig:
        response: LlmEvaluationOnlineConfig = self.stub.LlmEvaluationCreateOnlineConfig(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_online_config(
        self,
        request: GetLlmEvaluationOnlineConfigRequest,
    ) -> LlmEvaluationOnlineConfig:
        response: LlmEvaluationOnlineConfig = self.stub.LlmEvaluationGetOnlineConfig(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_online_configs(
        self,
        request: ListLlmEvaluationOnlineConfigsRequest,
    ) -> ListLlmEvaluationOnlineConfigsResponse:
        response: ListLlmEvaluationOnlineConfigsResponse = self.stub.LlmEvaluationListOnlineConfigs(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_online_config(
        self,
        request: UpdateLlmEvaluationOnlineConfigRequest,
    ) -> LlmEvaluationOnlineConfig:
        response: LlmEvaluationOnlineConfig = self.stub.LlmEvaluationUpdateOnlineConfig(request, metadata=self.metadata)
        return response

    def llm_evaluation_delete_online_config(self, request: DeleteLlmEvaluationOnlineConfigRequest) -> Empty:
        response: Empty = self.stub.LlmEvaluationDeleteOnlineConfig(request, metadata=self.metadata)
        return response

    def llm_evaluation_get_online_result(
        self,
        request: GetLlmEvaluationOnlineResultRequest,
    ) -> LlmEvaluationOnlineResult:
        response: LlmEvaluationOnlineResult = self.stub.LlmEvaluationGetOnlineResult(request, metadata=self.metadata)
        return response

    def llm_evaluation_list_online_results(
        self,
        request: ListLlmEvaluationOnlineResultsRequest,
    ) -> ListLlmEvaluationOnlineResultsResponse:
        response: ListLlmEvaluationOnlineResultsResponse = self.stub.LlmEvaluationListOnlineResults(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_get_annotation_queue_item(
        self,
        request: GetLlmEvaluationAnnotationQueueItemRequest,
    ) -> LlmEvaluationAnnotationQueueItem:
        response: LlmEvaluationAnnotationQueueItem = self.stub.LlmEvaluationGetAnnotationQueueItem(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_list_annotation_queue_items(
        self,
        request: ListLlmEvaluationAnnotationQueueItemsRequest,
    ) -> ListLlmEvaluationAnnotationQueueItemsResponse:
        response: ListLlmEvaluationAnnotationQueueItemsResponse = self.stub.LlmEvaluationListAnnotationQueueItems(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_update_annotation_queue_item(
        self,
        request: UpdateLlmEvaluationAnnotationQueueItemRequest,
    ) -> LlmEvaluationAnnotationQueueItem:
        response: LlmEvaluationAnnotationQueueItem = self.stub.LlmEvaluationUpdateAnnotationQueueItem(
            request, metadata=self.metadata
        )
        return response

    def llm_evaluation_promote_annotation_queue_item(
        self,
        request: PromoteLlmEvaluationAnnotationQueueItemRequest,
    ) -> PromoteLlmEvaluationAnnotationQueueItemResponse:
        response: PromoteLlmEvaluationAnnotationQueueItemResponse = self.stub.LlmEvaluationPromoteAnnotationQueueItem(
            request, metadata=self.metadata
        )
        return response
