# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from google.protobuf.empty_pb2 import Empty

from ondewo.nlu.llm_evaluation_pb2 import (
    AddLlmEvaluationExampleRequest,
    AddLlmEvaluationExamplesRequest,
    AddLlmEvaluationExamplesResponse,
    CancelLlmEvaluationExperimentRequest,
    CompareLlmEvaluationExperimentsRequest,
    CreateLlmEvaluationDatasetRequest,
    DeleteLlmEvaluationDatasetRequest,
    DeleteLlmEvaluationExampleRequest,
    DeleteLlmEvaluationExperimentRequest,
    DeleteLlmFeedbackRequest,
    GetLlmEvaluationDatasetRequest,
    GetLlmEvaluationExampleRequest,
    GetLlmEvaluationExperimentRequest,
    ListLlmEvaluationDatasetsRequest,
    ListLlmEvaluationDatasetsResponse,
    ListLlmEvaluationExamplesRequest,
    ListLlmEvaluationExamplesResponse,
    ListLlmEvaluationExperimentsRequest,
    ListLlmEvaluationExperimentsResponse,
    ListLlmFeedbackRequest,
    ListLlmFeedbackResponse,
    LlmEvaluationComparison,
    LlmEvaluationDataset,
    LlmEvaluationExample,
    LlmEvaluationExperiment,
    LlmFeedback,
    RunLlmEvaluationExperimentRequest,
    SubmitLlmFeedbackRequest,
    UpdateLlmEvaluationDatasetRequest,
    UpdateLlmEvaluationExampleRequest,
    UpdateLlmEvaluationExperimentRequest,
)
from ondewo.nlu.llm_evaluation_pb2_grpc import LlmEvaluationsStub
from ondewo.nlu.core.services_interface import ServicesInterface


class LlmEvaluations(ServicesInterface):
    """
    Exposes the LlmEvaluations-related endpoints of ONDEWO NLU services in a user-friendly way.

    See llm_evaluation.proto.
    """

    @property
    def stub(self) -> LlmEvaluationsStub:
        stub: LlmEvaluationsStub = LlmEvaluationsStub(channel=self.grpc_channel)
        return stub

    def create_dataset(self, request: CreateLlmEvaluationDatasetRequest) -> LlmEvaluationDataset:
        response: LlmEvaluationDataset = self.stub.CreateDataset(request, metadata=self.metadata)
        return response

    def get_dataset(self, request: GetLlmEvaluationDatasetRequest) -> LlmEvaluationDataset:
        response: LlmEvaluationDataset = self.stub.GetDataset(request, metadata=self.metadata)
        return response

    def list_datasets(self, request: ListLlmEvaluationDatasetsRequest) -> ListLlmEvaluationDatasetsResponse:
        response: ListLlmEvaluationDatasetsResponse = self.stub.ListDatasets(request, metadata=self.metadata)
        return response

    def update_dataset(self, request: UpdateLlmEvaluationDatasetRequest) -> LlmEvaluationDataset:
        response: LlmEvaluationDataset = self.stub.UpdateDataset(request, metadata=self.metadata)
        return response

    def delete_dataset(self, request: DeleteLlmEvaluationDatasetRequest) -> Empty:
        response: Empty = self.stub.DeleteDataset(request, metadata=self.metadata)
        return response

    def add_example(self, request: AddLlmEvaluationExampleRequest) -> LlmEvaluationExample:
        response: LlmEvaluationExample = self.stub.AddExample(request, metadata=self.metadata)
        return response

    def add_examples(self, request: AddLlmEvaluationExamplesRequest) -> AddLlmEvaluationExamplesResponse:
        response: AddLlmEvaluationExamplesResponse = self.stub.AddExamples(request, metadata=self.metadata)
        return response

    def get_example(self, request: GetLlmEvaluationExampleRequest) -> LlmEvaluationExample:
        response: LlmEvaluationExample = self.stub.GetExample(request, metadata=self.metadata)
        return response

    def list_examples(self, request: ListLlmEvaluationExamplesRequest) -> ListLlmEvaluationExamplesResponse:
        response: ListLlmEvaluationExamplesResponse = self.stub.ListExamples(request, metadata=self.metadata)
        return response

    def update_example(self, request: UpdateLlmEvaluationExampleRequest) -> LlmEvaluationExample:
        response: LlmEvaluationExample = self.stub.UpdateExample(request, metadata=self.metadata)
        return response

    def delete_example(self, request: DeleteLlmEvaluationExampleRequest) -> Empty:
        response: Empty = self.stub.DeleteExample(request, metadata=self.metadata)
        return response

    def run_experiment(self, request: RunLlmEvaluationExperimentRequest) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.RunExperiment(request, metadata=self.metadata)
        return response

    def get_experiment(self, request: GetLlmEvaluationExperimentRequest) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.GetExperiment(request, metadata=self.metadata)
        return response

    def list_experiments(self, request: ListLlmEvaluationExperimentsRequest) -> ListLlmEvaluationExperimentsResponse:
        response: ListLlmEvaluationExperimentsResponse = self.stub.ListExperiments(request, metadata=self.metadata)
        return response

    def update_experiment(self, request: UpdateLlmEvaluationExperimentRequest) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.UpdateExperiment(request, metadata=self.metadata)
        return response

    def delete_experiment(self, request: DeleteLlmEvaluationExperimentRequest) -> Empty:
        response: Empty = self.stub.DeleteExperiment(request, metadata=self.metadata)
        return response

    def cancel_experiment(self, request: CancelLlmEvaluationExperimentRequest) -> LlmEvaluationExperiment:
        response: LlmEvaluationExperiment = self.stub.CancelExperiment(request, metadata=self.metadata)
        return response

    def compare_experiments(self, request: CompareLlmEvaluationExperimentsRequest) -> LlmEvaluationComparison:
        response: LlmEvaluationComparison = self.stub.CompareExperiments(request, metadata=self.metadata)
        return response

    def submit_feedback(self, request: SubmitLlmFeedbackRequest) -> LlmFeedback:
        response: LlmFeedback = self.stub.SubmitFeedback(request, metadata=self.metadata)
        return response

    def list_feedback(self, request: ListLlmFeedbackRequest) -> ListLlmFeedbackResponse:
        response: ListLlmFeedbackResponse = self.stub.ListFeedback(request, metadata=self.metadata)
        return response

    def delete_feedback(self, request: DeleteLlmFeedbackRequest) -> Empty:
        response: Empty = self.stub.DeleteFeedback(request, metadata=self.metadata)
        return response
