# Copyright 2021-2025 ONDEWO GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ---------------------------------------------------------------------------
# THIS FILE IS AUTO-GENERATED by ondewo/nlu/scripts/generate_services.py
# DO NOT EDIT MANUALLY - your changes will be overwritten on the next run.
#
# To regenerate, run:
#   python3 ondewo/nlu/scripts/generate_services.py \
#       ondewo-nlu-api/ondewo/nlu ondewo/nlu/services
# ---------------------------------------------------------------------------

from typing import Iterator

from google.protobuf.empty_pb2 import Empty

from ondewo.nlu.rag_pb2 import (
    RagAddChunkRequest,
    RagAddChunkResponse,
    RagAddCrawlerResultsToDatasetsRequest,
    RagAgentCompletionRequest,
    RagAgentCompletionResponse,
    RagAgentList,
    RagAgentSessionList,
    RagAskRequest,
    RagAskResponse,
    RagChatAssistant,
    RagChatAssistantList,
    RagChatCompletionRequest,
    RagChatCompletionResponse,
    RagChatSession,
    RagChatSessionList,
    RagConstructKnowledgeGraphResponse,
    RagConstructRaptorResponse,
    RagCrawler,
    RagCrawlerResult,
    RagCreateAgentRequest,
    RagCreateChatAssistantRequest,
    RagCreateChatSessionRequest,
    RagCreateCrawlerRequest,
    RagCreateDatasetRequest,
    RagDataset,
    RagDatasetIdRequest,
    RagDatasetList,
    RagDeleteAgentRequest,
    RagDeleteAgentSessionsRequest,
    RagDeleteChatSessionsRequest,
    RagDeleteCrawlerRequest,
    RagDeleteCrawlerResponse,
    RagDeleteCrawlerRunsRequest,
    RagDeleteCrawlerRunsResponse,
    RagDeleteCrawlersRequest,
    RagDeleteCrawlersResponse,
    RagDeleteDocumentsRequest,
    RagDeleteRequest,
    RagDocument,
    RagDocumentList,
    RagDownloadDocumentRequest,
    RagFileChunk,
    RagGetCrawlerAttachedDatasetsRequest,
    RagGetCrawlerAttachedDatasetsResponse,
    RagGetCrawlerRequest,
    RagGetCrawlerResultRequest,
    RagGetCrawlerResultsRequest,
    RagGetCrawlerResultsResponse,
    RagGetCrawlerRunRequest,
    RagGetKnowledgeGraphResponse,
    RagListAgentSessionsRequest,
    RagListAgentsRequest,
    RagListChatAssistantsRequest,
    RagListChatSessionsRequest,
    RagListChunksRequest,
    RagListChunksResponse,
    RagListCrawlerRunsRequest,
    RagListCrawlerRunsResponse,
    RagListCrawlersRequest,
    RagListCrawlersResponse,
    RagListDatasetsRequest,
    RagListDocumentsRequest,
    RagParseDocumentsRequest,
    RagPartialSuccess,
    RagRelatedQuestionsRequest,
    RagRelatedQuestionsResponse,
    RagRemoveChunksRequest,
    RagRemoveCrawlerResultsFromDatasetsRequest,
    RagRetrievalRequest,
    RagRetrievalResponse,
    RagStartCrawlerRequest,
    RagStopCrawlerRequest,
    RagStopCrawlerResponse,
    RagStopParsingRequest,
    RagTaskStatus,
    RagUpdateAgentRequest,
    RagUpdateChatAssistantRequest,
    RagUpdateChatSessionRequest,
    RagUpdateChunkRequest,
    RagUpdateCrawlerRequest,
    RagUpdateDatasetRequest,
    RagUpdateDocumentRequest,
    RagUploadDocumentRequest,
)
from ondewo.nlu.rag_pb2_grpc import RagsStub
from ondewo.nlu.core.services_interface import ServicesInterface
from ondewo.nlu.operations_pb2 import Operation


class Rags(ServicesInterface):
    """
    Exposes the Rags-related endpoints of ONDEWO NLU services in a user-friendly way.

    See rag.proto.
    """

    @property
    def stub(self) -> RagsStub:
        stub: RagsStub = RagsStub(channel=self.grpc_channel)
        return stub

    def rag_create_dataset(self, request: RagCreateDatasetRequest) -> RagDataset:
        response: RagDataset = self.stub.RagCreateDataset(request, metadata=self.metadata)
        return response

    def rag_update_dataset(self, request: RagUpdateDatasetRequest) -> RagDataset:
        response: RagDataset = self.stub.RagUpdateDataset(request, metadata=self.metadata)
        return response

    def rag_delete_datasets(self, request: RagDeleteRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = self.stub.RagDeleteDatasets(request, metadata=self.metadata)
        return response

    def rag_list_datasets(self, request: RagListDatasetsRequest) -> RagDatasetList:
        response: RagDatasetList = self.stub.RagListDatasets(request, metadata=self.metadata)
        return response

    def rag_upload_document(self, request: Iterator[RagUploadDocumentRequest]) -> RagDocument:
        response: RagDocument = self.stub.RagUploadDocument(request, metadata=self.metadata)
        return response

    def rag_update_document(self, request: RagUpdateDocumentRequest) -> RagDocument:
        response: RagDocument = self.stub.RagUpdateDocument(request, metadata=self.metadata)
        return response

    def rag_download_document(self, request: RagDownloadDocumentRequest) -> Iterator[RagFileChunk]:
        response: Iterator[RagFileChunk] = self.stub.RagDownloadDocument(request, metadata=self.metadata)
        return response

    def rag_list_documents(self, request: RagListDocumentsRequest) -> RagDocumentList:
        response: RagDocumentList = self.stub.RagListDocuments(request, metadata=self.metadata)
        return response

    def rag_delete_documents(self, request: RagDeleteDocumentsRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = self.stub.RagDeleteDocuments(request, metadata=self.metadata)
        return response

    def rag_retrieval(self, request: RagRetrievalRequest) -> RagRetrievalResponse:
        response: RagRetrievalResponse = self.stub.RagRetrieval(request, metadata=self.metadata)
        return response

    def rag_get_knowledge_graph(self, request: RagDatasetIdRequest) -> RagGetKnowledgeGraphResponse:
        response: RagGetKnowledgeGraphResponse = self.stub.RagGetKnowledgeGraph(request, metadata=self.metadata)
        return response

    def rag_delete_knowledge_graph(self, request: RagDatasetIdRequest) -> Empty:
        response: Empty = self.stub.RagDeleteKnowledgeGraph(request, metadata=self.metadata)
        return response

    def rag_construct_knowledge_graph(self, request: RagDatasetIdRequest) -> RagConstructKnowledgeGraphResponse:
        response: RagConstructKnowledgeGraphResponse = \
            self.stub.RagConstructKnowledgeGraph(request, metadata=self.metadata)
        return response

    def rag_knowledge_graph_status(self, request: RagDatasetIdRequest) -> RagTaskStatus:
        response: RagTaskStatus = self.stub.RagKnowledgeGraphStatus(request, metadata=self.metadata)
        return response

    def rag_construct_raptor(self, request: RagDatasetIdRequest) -> RagConstructRaptorResponse:
        response: RagConstructRaptorResponse = self.stub.RagConstructRaptor(request, metadata=self.metadata)
        return response

    def rag_raptor_status(self, request: RagDatasetIdRequest) -> RagTaskStatus:
        response: RagTaskStatus = self.stub.RagRaptorStatus(request, metadata=self.metadata)
        return response

    def rag_parse_documents(self, request: RagParseDocumentsRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = self.stub.RagParseDocuments(request, metadata=self.metadata)
        return response

    def rag_stop_parsing(self, request: RagStopParsingRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = self.stub.RagStopParsing(request, metadata=self.metadata)
        return response

    def rag_list_chunks(self, request: RagListChunksRequest) -> RagListChunksResponse:
        response: RagListChunksResponse = self.stub.RagListChunks(request, metadata=self.metadata)
        return response

    def rag_add_chunk(self, request: RagAddChunkRequest) -> RagAddChunkResponse:
        response: RagAddChunkResponse = self.stub.RagAddChunk(request, metadata=self.metadata)
        return response

    def rag_remove_chunks(self, request: RagRemoveChunksRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = self.stub.RagRemoveChunks(request, metadata=self.metadata)
        return response

    def rag_update_chunk(self, request: RagUpdateChunkRequest) -> Empty:
        response: Empty = self.stub.RagUpdateChunk(request, metadata=self.metadata)
        return response

    def rag_create_chat_assistant(self, request: RagCreateChatAssistantRequest) -> RagChatAssistant:
        response: RagChatAssistant = self.stub.RagCreateChatAssistant(request, metadata=self.metadata)
        return response

    def rag_update_chat_assistant(self, request: RagUpdateChatAssistantRequest) -> Empty:
        response: Empty = self.stub.RagUpdateChatAssistant(request, metadata=self.metadata)
        return response

    def rag_delete_chat_assistants(self, request: RagDeleteRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = self.stub.RagDeleteChatAssistants(request, metadata=self.metadata)
        return response

    def rag_list_chat_assistants(self, request: RagListChatAssistantsRequest) -> RagChatAssistantList:
        response: RagChatAssistantList = self.stub.RagListChatAssistants(request, metadata=self.metadata)
        return response

    def rag_create_agent(self, request: RagCreateAgentRequest) -> Empty:
        response: Empty = self.stub.RagCreateAgent(request, metadata=self.metadata)
        return response

    def rag_update_agent(self, request: RagUpdateAgentRequest) -> Empty:
        response: Empty = self.stub.RagUpdateAgent(request, metadata=self.metadata)
        return response

    def rag_delete_agent(self, request: RagDeleteAgentRequest) -> Empty:
        response: Empty = self.stub.RagDeleteAgent(request, metadata=self.metadata)
        return response

    def rag_list_agents(self, request: RagListAgentsRequest) -> RagAgentList:
        response: RagAgentList = self.stub.RagListAgents(request, metadata=self.metadata)
        return response

    def rag_create_chat_session(self, request: RagCreateChatSessionRequest) -> RagChatSession:
        response: RagChatSession = self.stub.RagCreateChatSession(request, metadata=self.metadata)
        return response

    def rag_update_chat_session(self, request: RagUpdateChatSessionRequest) -> Empty:
        response: Empty = self.stub.RagUpdateChatSession(request, metadata=self.metadata)
        return response

    def rag_list_chat_sessions(self, request: RagListChatSessionsRequest) -> RagChatSessionList:
        response: RagChatSessionList = self.stub.RagListChatSessions(request, metadata=self.metadata)
        return response

    def rag_delete_chat_sessions(self, request: RagDeleteChatSessionsRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = self.stub.RagDeleteChatSessions(request, metadata=self.metadata)
        return response

    def rag_list_agent_sessions(self, request: RagListAgentSessionsRequest) -> RagAgentSessionList:
        response: RagAgentSessionList = self.stub.RagListAgentSessions(request, metadata=self.metadata)
        return response

    def rag_delete_agent_sessions(self, request: RagDeleteAgentSessionsRequest) -> RagPartialSuccess:
        response: RagPartialSuccess = self.stub.RagDeleteAgentSessions(request, metadata=self.metadata)
        return response

    def rag_chat_completion(self, request: RagChatCompletionRequest) -> Iterator[RagChatCompletionResponse]:
        response: Iterator[RagChatCompletionResponse] = self.stub.RagChatCompletion(request, metadata=self.metadata)
        return response

    def rag_agent_completion(self, request: RagAgentCompletionRequest) -> Iterator[RagAgentCompletionResponse]:
        response: Iterator[RagAgentCompletionResponse] = self.stub.RagAgentCompletion(request, metadata=self.metadata)
        return response

    def rag_ask(self, request: RagAskRequest) -> Iterator[RagAskResponse]:
        response: Iterator[RagAskResponse] = self.stub.RagAsk(request, metadata=self.metadata)
        return response

    def rag_related_questions(self, request: RagRelatedQuestionsRequest) -> RagRelatedQuestionsResponse:
        response: RagRelatedQuestionsResponse = self.stub.RagRelatedQuestions(request, metadata=self.metadata)
        return response

    def rag_create_crawler(self, request: RagCreateCrawlerRequest) -> RagCrawler:
        response: RagCrawler = self.stub.RagCreateCrawler(request, metadata=self.metadata)
        return response

    def rag_get_crawler(self, request: RagGetCrawlerRequest) -> RagCrawler:
        response: RagCrawler = self.stub.RagGetCrawler(request, metadata=self.metadata)
        return response

    def rag_list_crawlers(self, request: RagListCrawlersRequest) -> RagListCrawlersResponse:
        response: RagListCrawlersResponse = self.stub.RagListCrawlers(request, metadata=self.metadata)
        return response

    def rag_update_crawler(self, request: RagUpdateCrawlerRequest) -> RagCrawler:
        response: RagCrawler = self.stub.RagUpdateCrawler(request, metadata=self.metadata)
        return response

    def rag_delete_crawler(self, request: RagDeleteCrawlerRequest) -> RagDeleteCrawlerResponse:
        response: RagDeleteCrawlerResponse = self.stub.RagDeleteCrawler(request, metadata=self.metadata)
        return response

    def rag_start_crawler(self, request: RagStartCrawlerRequest) -> Operation:
        response: Operation = self.stub.RagStartCrawler(request, metadata=self.metadata)
        return response

    def rag_stop_crawler(self, request: RagStopCrawlerRequest) -> RagStopCrawlerResponse:
        response: RagStopCrawlerResponse = self.stub.RagStopCrawler(request, metadata=self.metadata)
        return response

    def rag_get_crawler_run(self, request: RagGetCrawlerRunRequest) -> Operation:
        response: Operation = self.stub.RagGetCrawlerRun(request, metadata=self.metadata)
        return response

    def rag_list_crawler_runs(self, request: RagListCrawlerRunsRequest) -> RagListCrawlerRunsResponse:
        response: RagListCrawlerRunsResponse = self.stub.RagListCrawlerRuns(request, metadata=self.metadata)
        return response

    def rag_delete_crawler_runs(self, request: RagDeleteCrawlerRunsRequest) -> RagDeleteCrawlerRunsResponse:
        response: RagDeleteCrawlerRunsResponse = self.stub.RagDeleteCrawlerRuns(request, metadata=self.metadata)
        return response

    def rag_get_crawler_result(self, request: RagGetCrawlerResultRequest) -> RagCrawlerResult:
        response: RagCrawlerResult = self.stub.RagGetCrawlerResult(request, metadata=self.metadata)
        return response

    def rag_get_crawler_results(self, request: RagGetCrawlerResultsRequest) -> RagGetCrawlerResultsResponse:
        response: RagGetCrawlerResultsResponse = self.stub.RagGetCrawlerResults(request, metadata=self.metadata)
        return response

    def rag_add_crawler_results_to_datasets(self, request: RagAddCrawlerResultsToDatasetsRequest) -> Operation:
        response: Operation = self.stub.RagAddCrawlerResultsToDatasets(request, metadata=self.metadata)
        return response

    def rag_remove_crawler_results_from_datasets(
        self,
        request: RagRemoveCrawlerResultsFromDatasetsRequest,
    ) -> Operation:
        response: Operation = self.stub.RagRemoveCrawlerResultsFromDatasets(request, metadata=self.metadata)
        return response

    def rag_get_crawler_attached_datasets(
        self,
        request: RagGetCrawlerAttachedDatasetsRequest,
    ) -> RagGetCrawlerAttachedDatasetsResponse:
        response: RagGetCrawlerAttachedDatasetsResponse = \
            self.stub.RagGetCrawlerAttachedDatasets(request, metadata=self.metadata)
        return response

    def rag_delete_crawlers(self, request: RagDeleteCrawlersRequest) -> RagDeleteCrawlersResponse:
        response: RagDeleteCrawlersResponse = self.stub.RagDeleteCrawlers(request, metadata=self.metadata)
        return response
